openapi: 3.0.0
info:
  description: "Product Microservice description."
  version: "1.0.0"
  title: "Shop Microservice"
tags:
- name: "Shop"
paths:
    /v1/shop/{id}:
      get:
        tags:
          - Shop
        description: Get Shop By ID
        parameters:
            - in: header
              name: local
              required: false
              schema:
                type: string
                description: language to return the data based on it
                enum: [ar-SA, en-US, Multi]
            - in: path
              name: id
              required: true
              schema:
                type: string
              description: shop Id
            - in: query
              name: nearest
              required: false
              schema:
                type: string
                description: get nearest shops by location
                enum: [true]
            - in: query
              name: long
              required: false
              schema:
                type: double
                description: user location longitude
            - in: query
              name: lat
              required: false
              schema:
                type: double
                description: user location latitude
            - in: query
              name: available
              required: false
              schema:
                type: boolean
                enum: [true]
        responses:
          '200':
            description: Auto generated using Swagger Inspector
            content:
              application/json; charset=utf-8:
                schema:
                  type: string
                examples: {}
